### ISSUE TITLE
images are missed after changing the path

### ISSUE THREAD

**Issue by KaterynaZhykharieva** [mrlss/generator-scaffolder#206]
Project type - markup only, Tailwind, no engine. Windows 10

We have 4 source folders after running the developer mode https://s3.amazonaws.com/tz9i2p4ymw/kd7s06h824l15f66j310.jpg
After changing the destination of images in config file, they are not displayed in Sources tab of developer tools
https://s3.amazonaws.com/tz9i2p4ymw/70qtu6h30709o37rw719.jpg
Console errors - https://s3.amazonaws.com/tz9i2p4ymw/70o64q1p78123q23wm0.jpg

**Comment by AlekseyRozhkov** [comment]
This is work as it should, sorry for confusion.
The problem is that after new `dest` folder for images was added - you need to change paths for images src in HTML also, here results:
w/o changing path in HTML but with changed path on config - https://scrstorage.s3.amazonaws.com/Image_NWmGHb2y68.jpg - we got an error
changed config + changed paths - https://scrstorage.s3.amazonaws.com/Image_TSzChhKw9V.jpg - everything works and images folder appear in source tree.

Until assets are not loaded to the page - they will not appear in source tree.
